### ISSUE TITLE
Should we change the way mutations are made?

### ISSUE THREAD

**Issue by ptoonen** [infosupport/stryker-net#14]
Currently SyntaxNodes are being cast as a BinaryExpressionSyntax. This limits the amount of SyntaxKinds we can check for. Should we change this to more generic form so we can group mutators accordingly, or shall we adhere to Roslyn's *ExpressionSyntaxes?

**Comment by simondel** [comment]
Do you have an example of a generic form? We can of course support other types of `SyntaxNodes`, they are just not interesting for a `BinaryExpressionSyntaxMutator`.
