### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by carlosschults** [infosupport/stryker-net#18]
Hey everyone.

I've been looking for a mutation testing tool for .Net for a while, and I was very pleased to find out about stryker.net (via the project's website). I really wish I could start using it in production right away!

But I wonder what's the current status of the project, since it's been more than 5 months since [the last commit](https://github.com/infosupport/stryker-net/commit/6d1c82889a746220e4185ded626cb8e295789245).

I don't think I am knowledgeable enough to help you write the mutators themselves, but if there is any other I could you with the project, I'd be very happy to do it!

**Comment by ptoonen** [comment]
Hi Carlos,

Although there hasn’t been a lot (any) activity as of late - we are continuing the effort. You can expect more news/progress by the end of the month :)

- Peter

**Comment by carlosschults** [comment]
Hi @ptoonen , 

I'm glad to hear that! I will stay tuned then. :)

Thanks!
