### ISSUE TITLE
Execute tests

### ISSUE THREAD

**Issue by simondel** [infosupport/stryker-net#2]
A core part of a mutation testing framework is the ability to execute tests to confirm that the unit tests pass without mutations and to test if a mutation can be detected.

Investigate if it's possible to support MSTest, NUnit and XUnit with one single solution.

**Comment by simondel** [comment]
The example of Piotr can be very useful for this, thanks @ptoonen! http://benetkiewicz.github.io/blog/csharp/roslyn/2014/10/26/code-mutiations-with-roslyn.html

**Comment by wmeints** [comment]
I guess you can use the different test runners. The popular test frameworks have test runners that you can execute from code.

**Comment by pavzaj** [comment]
@simondel, what exactly do you mean by " support MSTest, NUnit and XUnit with one single solution"?
Every framework has different runner, but of course we should think about some abstraction layer over that runners, some canonical inputs, operations and outputs common to all frameworks.
Under that abstraction layer we could have various ways to execute tests. We could use dedicated test runners CLI or some runner libraries in runtime as @wmeints suggested.

The following idea is not clear to me yet, but I think we should allow end users to execute tests the same way as they do it in their build servers. We shouldn't override test execution if it's possible. I some one have his custom script to run tests, we could just mimic this script to run on mutated assemblies and capture results. "dotnet.exe test" command could help.

There are a lot of features of PITest that we probably want to copy (http://pitest.org/java_mutation_testing_systems/), like coverage based test selection , coverage based mutation insertion, incremental analysis etc (http://pitest.org/quickstart/incremental_analysis/).

**Comment by pavzaj** [comment]
It looks like incremental mutation testing has some scientific foundations:
http://www.sciencedirect.com/science/article/pii/S1571066113000145

**Comment by simondel** [comment]
You want to execute the tests in some way that still resembles the way they are normally executed. Selecting which tests are required to test (if any) each mutation really speeds up the process. Incremental analysis is something that's far on the horizon as there are plenty of other challenges ahead ;)

**Comment by pavzaj** [comment]
We could also use CI system integration features like xUnit and Nunit provide for Teamcity to capture test execution output.
Like --teamcity for Nunit (https://github.com/nunit/docs/wiki/Console-Command-Line) and -teamcity for xUnit (https://xunit.github.io/docs/getting-test-results-in-teamcity.html).
I'm not sure how mstest can handle this.
