### ISSUE TITLE
Explore .NET Core support

### ISSUE THREAD

**Issue by ptoonen** [infosupport/stryker-net#6]
There were some issues with Roslyn before .NET Standard 1.3 but this shouldn't be an issue now. Let's see if it's possible.

**Comment by simondel** [comment]
I tried to install the latest `Microsoft.CodeAnalysis` package in a .NET Core console app but it failed:
```
Installing System.Xml.XPath 4.3.0.
Installing System.Xml.XPath.XDocument 4.3.0.
Installing System.ValueTuple 4.3.0.
Installing System.Collections.Immutable 1.3.1.
Installing System.Reflection.Metadata 1.4.2.
Installing System.Diagnostics.FileVersionInfo 4.3.0.
Installing System.Xml.XmlDocument 4.3.0.
Installing System.Text.Encoding.CodePages 4.3.0.
Installing System.Diagnostics.StackTrace 4.3.0.
Installing Microsoft.CodeAnalysis.Common 2.0.0-rc4.
Installing System.Diagnostics.Contracts 4.3.0.
Installing Microsoft.CodeAnalysis 2.0.0-rc4.
Installing Microsoft.CodeAnalysis.VisualBasic 2.0.0-rc4.
Installing Microsoft.CodeAnalysis.CSharp 2.0.0-rc4.
Installing Microsoft.CodeAnalysis.Workspaces.Common 2.0.0-rc4.
Installing Microsoft.CodeAnalysis.VisualBasic.Workspaces 2.0.0-rc4.
Installing Microsoft.CodeAnalysis.CSharp.Workspaces 2.0.0-rc4.
Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
One or more packages are incompatible with .NETCoreApp,Version=v1.1.
Package restore failed. Rolling back package changes for 'Stryker.NET'.
```

**Comment by simondel** [comment]
This may help us: https://github.com/dotnet/corefx/issues/9788

**Comment by ptoonen** [comment]
Waiting for new image in appveyor: https://github.com/appveyor/ci/issues/1176

**Comment by simondel** [comment]
Wow, 43825f47bae5a2f78cf57cbb953cb8dac9c4ace1 really shows how much cleaner .NET Core projects are. I like it!

**Comment by ptoonen** [comment]
I'm at the point where I can start using it, but not sure how to get OpenCover to work with it :)

**Comment by ptoonen** [comment]
Okay, so this will be an issue: https://jira.sonarsource.com/browse/SONARMSBRU-288

**Comment by pavzaj** [comment]
About OpenCover. It might be not possible yet, as there is no Nunit console runner capable of running .NET Core. There is some PreRelease alternative:
http://www.alteridem.net/2016/06/18/nunit-3-testing-net-core-rc2/

**Comment by ptoonen** [comment]
I switched to XUnit for this reason; they do have a runner but for some reason the AppVeyor image doesn't like piping to trx format. Will look into that tonight.

**Comment by ptoonen** [comment]
Although it is possible to run this in .NET core, it's impossible to perform OpenCover and/or SonarQube analysis as of this moment. I very much doubt that OpenCover will be able to support it [anytime soon](https://github.com/OpenCover/opencover/issues/601) and SonarQube is also doubtful: https://jira.sonarsource.com/browse/SONARMSBRU-167

So I'm halting work on this. Unfortunately.

**Comment by ptoonen** [comment]
I couldn't resist. Had to try. And it worked. Replacing OpenCover by DotCover (which has a [free CLI license](https://www.jetbrains.com/dotcover/download/command_line_license.html)) and inserting a few fake ProjectGuid's + manually copying the targets has led to a working build :)
