### ISSUE TITLE
Add Visual Studio plugin

### ISSUE THREAD

**Issue by wmeints** [infosupport/stryker-net#8]
It would be awesome to have a Visual Studio runner for this. I think it will increase developer adoption and make life in general much better.

**Comment by simondel** [comment]
I agree! Perhaps we can look at [Visual Mutator](https://visualmutator.github.io/web/) to see what they did. As far as I know, [this](https://github.com/pavzaj/visualmutator) is the most up-to-date fork.

**Comment by nicojs** [comment]
Can you explain to me why you call this "Visual Studio test runner"? Is this a test runner in terms of Stryker? Or is this a term inside visual studio?

I wouldn't like a Stryker test runner plugin which only works in Visual Studio. I'm planning to use vscode :).

**Comment by simondel** [comment]
Because it allows you to run Stryker from Visual Studio. Under the hood it will probably just call the Stryker commandline API and report the results in a visual way. 

You could compare it to a scenario where you'd use grunt-stryker and stryker-html-reporter to run Stryker.

**Comment by nicojs** [comment]
Right 👍 , renamed the issue for clarity

**Comment by wmeints** [comment]
Yes, the idea is this. I want to be able to run mutation testing from VS Code, VS and commandline as well. Maybe we can make it so that other people can write plugins for tools like Atom that interface with Stryker.NET in some way.

**Comment by ptoonen** [comment]
I think CLI should be the first and foremost focus. From there we can do anything, including custom plugins/extensions for Visual Studio (code) :-)

**Comment by pavzaj** [comment]
I agree that CLI is most important type of interaction with future Stryker.NET. It's easiest to test and it opens Mutation Testing a way to various Continous-Whatever pipelines.

What do you think about extracting mutation logic to separate assembly?
Now mutation logic is inside CLI and this could could cause problems with developing other interaction interfaces in future.
